name: Breezy Weather Debug Build CI

on:
  push:
    branches:
      - main
    tags:
      - v*

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Gradle Wrapper
        uses: gradle/actions/wrapper-validation@v3

      - name: Setup Android SDK
        run: |
          sudo apt-get update
          sudo apt-get install -y --no-install-recommends android-sdk
          echo "sdk.dir=$ANDROID_SDK_ROOT" > local.properties
          ${ANDROID_SDK_ROOT}/cmdline-tools/latest/bin/sdkmanager "build-tools;29.0.3"

      - name: Set up JDK
        uses: actions/setup-java@v4
        with:
          java-version: 17
          distribution: adopt

      - name: Set up Gradle and Build Debug
        uses: gradle/actions/setup-gradle@v3
        with:
          arguments: |
            assembleFreenetDebug
            assembleBasicDebug

      - name: Check for APK files
        run: |
          echo "Listing APK files after build:"
          find app/build/outputs/apk -name "*.apk" -exec ls -lh {} \;

      - name: Upload Debug APKs as artifacts
        uses: actions/upload-artifact@v3
        with:
          name: Debug APKs
          path: |
            app/build/outputs/apk/basic/debug/app-basic-arm64-*.apk
            app/build/outputs/apk/freenet/debug/app-freenet-arm64-*.apk

      - name: Create release
        if: startsWith(github.ref, 'refs/tags/') && github.repository == 'breezy-weather/breezy-weather'
        uses: softprops/action-gh-release@v2
        with:
          tag_name: ${{ env.VERSION_TAG }}
          name: Breezy Weather Debug ${{ env.VERSION_TAG }}
          body: |
            **Don’t know which release to choose? Check [INSTALL instructions](https://github.com/breezy-weather/breezy-weather/blob/main/INSTALL.md).**

            ---

            ### Checksums
            | Flavor        | Variant     | SHA-256                                |
            |---------------|-------------|----------------------------------------|
            | Standard      | Universal   | ${{ env.APK_STANDARD_SHA256 }}         |
            | Free networks | Universal   | ${{ env.APK_FREENET_SHA256 }}          |
          files: |
            app/build/outputs/apk/basic/debug/app-basic-arm64-*.apk
            app/build/outputs/apk/freenet/debug/app-freenet-arm64-*.apk
          draft: true
          prerelease: false
